spring:
  rabbitmq:
    host: localhost          # O endereço do servidor RabbitMQ
    port: 5672               # A porta padrão do RabbitMQ
    username: guest          # Nome de usuário (padrão é 'guest')
    password: guest          # Senha (padrão é 'guest')
    listener:
      simple:
        concurrency: 5       # Número de consumidores simultâneos
        max-concurrency: 10   # Número máximo de consumidores simultâneos
        retry:
          enabled: true       # Ativa a política de retry
          initial-interval: 1000 # Intervalo inicial em milissegundos
          multiplier: 2.0      # Multiplicador para tentativas
          max-attempts: 5      # Número máximo de tentativas
          max-interval: 10000   # Intervalo máximo entre as tentativas
