# Dockerfile
FROM rabbitmq:management

# Copie quaisquer arquivos de configuração personalizados, se necessário
# COPY ./my-rabbitmq.conf /etc/rabbitmq/rabbitmq.conf

# Exponha as portas necessárias
EXPOSE 5672 15672
